COUNTRY_CODES = {
    "AG": "Antigua and Barbuda",
    "AR": "Argentina",
    "AU": "Australia",
    "BS": "Bahamas",
    "BH": "Bahrain",
    "BB": "Barbados",
    "BE": "Belgium",
    "BM": "Bermuda",
    "BW": "Botswana",
    "BR": "Brazil",
    "BG": "Bulgaria",
    "CA": "Canada",
    "KY": "Cayman Islands",
    "CL": "Chile",
    "FR": "France",
    "DE": "Germany",
    "GH": "Ghana",
    "IN": "India",
    "IE": "Ireland",
    "IL": "Israel",
    "IT": "Italy",
    "JM": "Jamaica",
    "KW": "Kuwait",
    "LU": "Luxembourg",
    "NA": "Namibia",
    "NL": "Netherlands",
    "NZ": "New Zealand",
    "NG": "Nigeria",
    "NO": "Norway",
    "PH": "Philippines",
    "KN": "Saint Kitts and Nevis",
    "SA": "Saudi Arabia",
    "ZA": "South Africa",
    "SE": "Sweden",
    "CH": "Switzerland",
    "TH": "Thailand",
    "TT": "Trinidad and Tobago",
    "AE": "United Arab Emirates",
    "GB": "United Kingdom",
    "US": "United States",
}

COUNTRY_NAMES = dict([(x[1],x[0]) for x in COUNTRY_CODES.items()])
